# Generated by Django 4.1.7 on 2023-02-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantharooapp', '0005_filehistorynotallowspam'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSeenDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('numberOfSeen', models.IntegerField()),
                ('lastseenTime', models.TimeField(auto_now=True)),
                ('lastSeen', models.DateField(auto_now=True)),
            ],
        ),
    ]
